# Expect 200
POST http://localhost:3001/api/contacts
Content-Type: application/json

{ 
  "name": "Lucas Piedrahita", 
  "number": "9192743568"
}

### Expect 400: name of contact is missing
POST http://localhost:3001/api/contacts
Content-Type: application/json

{ 
  "number": "9192743568"
}

### Expect 400: number of contactis missing
POST http://localhost:3001/api/contacts
Content-Type: application/json

{ 
  "name": "Lucas Piedrahita" 
}

### Expect 400: name must be unique
POST http://localhost:3001/api/contacts
Content-Type: application/json

{ 
  "name": "Lucas Piedrahita", 
  "number": "9192743568"
}